# -*- coding: utf-8 -*-
"""Bart&T-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18BgvncerSgsnUGDfG0x7RL6QVZsRcj9u
"""

#installing transformers
pip install transformers

#importing libraries
from transformers import pipeline
import os

#setting gpu
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

# BART model to use
summarizer1 = pipeline("summarization")

#t-5 model trained on c4 common crawl web corpus
summarizer2 = pipeline("summarization", model="t5-base", tokenizer="t5-base", framework="tf")

text1="""US President Donald Trump has called the White House a ?real dump?, and said that he preferred staying at his own properties rather than at the executive mansion, a media report said.The White House did not immediately respond to a request for comment about the account, which appeared on the website Golf.com. The hotelier-turned-POTUS reportedly told members of his Trump National Golf Course in Bedminster, New Jersey, that he preferred staying at his own properties rather than at 1600 Pennsylvania Ave NW, because the executive mansion is ?a real dump?, the Washington Post reported, citing the article on Golf.com as saying.Trump, in a May interview with Time magazine, had praised the White House for its ?beautiful kitchen?, ?amazing? phone system and ?incredible? historical furniture. ?People have no idea the beauty of the White House. The real beauty of the White House,? Trump earlier said.Meanwhile, taking aim at the US President, former first daughter Chelsea Clinton, who spent most of her teen years as a White House resident spoke out in support of the White House staff, thanking the ?ushers, butlers, maids, chefs, florists,? etc, for all the hard work they do.Representative Dina Titus, a Democrat, also urged Trump to take his family and move out of the White House if he was unhappy with conditions.Trump spent a good deal of time away from the White House, including 21 of his first 26 weekends, according to CNN count, mostly at his luxury Mar-a-Lago resort in Palm Beach, Florida."""

text2 = """One month after the United States began what has become a troubled rollout of a national COVID vaccination campaign, the effort is finally gathering real steam.
Close to a million doses -- over 951,000, to be more exact -- made their way into the arms of Americans in the past 24 hours, the U.S. Centers for Disease Control and Prevention reported Wednesday. That's the largest number of shots given in one day since the rollout began and a big jump from the previous day, when just under 340,000 doses were given, CBS News reported.
That number is likely to jump quickly after the federal government on Tuesday gave states the OK to vaccinate anyone over 65 and said it would release all the doses of vaccine it has available for distribution. Meanwhile, a number of states have now opened mass vaccination sites in an effort to get larger numbers of people inoculated, CBS News reported."""

#printing the summary1 using BART Model
summary_text1 = summarizer1(text1, max_length=100, min_length=5, do_sample=False)[0]['summary_text']
print(summary_text1)

#printing the summary1 using T-5 Model
summary_text1 = summarizer2(text1, max_length=100, min_length=5, do_sample=False)[0]['summary_text']
print(summary_text1)

#printing the summary2 using BART model
summary_text2 = summarizer1(text2, max_length=100, min_length=5, do_sample=False)[0]['summary_text']
print(summary_text2)

#printing the summary2 using T-5 model
summary_text2 = summarizer2(text2, max_length=100, min_length=5, do_sample=False)[0]['summary_text']
print(summary_text2)