# -*- coding: utf-8 -*-
"""extractive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1miaw0RQ4beoEWHkywiDtlbz2RuDZ73mi
"""

#!pip install transformers

#!pip install datasets
#!pip install contractions
#!pip install difflib

#!pip install rouge

import gensim  
import rouge 
import difflib
from tensorflow.keras import callbacks, models, layers, preprocessing as kprocessing #(2.6.0)## for bart
import transformers  #(3.0.1)
import datasets  
import pandas as pd  
import re
import nltk  
import contractions

dataset = datasets.load_dataset("cnn_dailymail", '3.0.0')
lst_dics = [dic for dic in dataset["train"]]
dtf = pd.DataFrame(lst_dics).rename(columns={"article":"text", "highlights":"y"})[["text","y"]].head(20000)
dtf.head()

df_train = dtf.iloc[i+1:]
df_test = dtf.iloc[:i+1]

print(df_test["text"][0])

def textrank(corpus, ratio=0.5):    
    if type(corpus) is str:        
       corpus = [corpus]    
    lst_summaries = [gensim.summarization.summarize(txt,  
                     ratio=ratio) for txt in corpus]    
    return lst_summaries
## Apply the function to corpus
predicted = textrank(df_test["text"], 0.5)
predicted[i]

def find_ex_sum(text):
  sum = gensim.summarization.summarize(txt,  ratio=0.5)

txt = """It's been some time since Facebook's Mark Zuckerberg went meta on us but 
if recent reports are to be considered true, the endevour of Metaverse hasn't gained 
pace that it was expected to. But now an island nation in the Pacific Ocean may start a 
new trend, not because of any pleasant reason. Tuvalu, the island country in southern Pacific Ocean, 
is planning to build a digital version of itself.Reason? Climate Change is threatening the very existence of 
Tuvalu. The country's foreign minister announced the metaverse plans in the ongoing COP27 climate summit. Foreign
 Minister Simon Kofe it was time to look at alternative solutions for his country's survival, and that included 
 Tuvalu becoming the first digitised nation in the metaverse – an online realm that uses augmented and 
 virtual reality (VR) to help users interact. Kofe gave his video address standing on a digital replica of 
 an islet threatened by rising sea levels. This is not the first time Kofe has hit the headlines. 
 Last year, in COP26 summit, he addressed those present while standing in knee-deep seawater. 
 He sought to underline threat to his nation due to rising sea levels, an effect triggered by climate change. 
 Tuvalu will be the first country to replicate itself in the metaverse, but follows both the city of Seoul and the island nation of Barbados, 
 which last year said they would enter the metaverse to provide administrative and consular services, respectively."""

sum = find_ex_sum(txt)

print(sum)